[package]
name = "arrow-flightsql-odbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#odbc-api = "0.36.1"
arrow-odbc = "0.9.1"
